{{- if .Values.storage.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: storage-config
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
data:
  module_conf.json: |
    {}
{{- end }}