{{- if .Values.realtime.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: realtime-config
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
data:
  latest_remote_poll.txt: |  
     {{ now | date "2023-6-10" | quote }}
{{- end }}
